version: '3'


services:
  redis:
    image: redis:7.0.12
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  python:
    build: .
    restart: always
    depends_on:
      - redis
